#!/bin/bash -x


a=$1
name_rep=/Users/lauvergn/trav/QModLib-old

if test $a = "+"
then
  echo with +
  aold=`grep QML  version-QML | awk '{print $3}' | awk -F. '{print $1 " " $2}'`
  echo $aold

  if test $a = "+"
  then
    a=`echo $aold | awk '{print $1 "." $2+1}'`
  else
    a=`echo $aold | awk '{print $1 "." $2}'`
  fi

  echo $a

fi
name_sd="QModLib-v"$a


name=$name_rep/$name_sd

if test -s $name  
then
    echo The directory $name exists !!
else
    echo le repertoire $name does not exist

    #modify the version in versionQML
    echo "QML =  "$a >  version-QML
    

    mkdir $name

    cp -r * $name

    cd $name
    make clean


fi

cd $name_rep

name_tar=QML.$a
echo $name_tar.tar
tar cvf $name_tar.tar $name_sd
gzip $name_tar.tar
#scp $name_tar.tar.gz styx2:/u/lauvergn/trav/QModLib
 scp $name_tar.tar.gz styx2:/userTMP/lauvergn/QModLib

