#!/bin/bash

here=`pwd`

cd ..
 make dnS > $here/comp.log 2>&1
cd  $here

nbOK=`grep -c "dnS compilation: OK" comp.log`

echo "=========================================="
echo " TESTING the dnS module"

if [ "$nbOK" = 0 ]
then
  echo " dnS compilation ERROR"
  exit
fi

echo "   OPT: " $ExternalOPT
echo "   OMP: " $ExternalOMP
echo "=========================================="

../dnS.x > res_dnS

echo "TESTING operators: == /= > >= < <= and .eq. ..."

nb_pb1=`grep -c "F ? T" res_dnS`
nb_pb2=`grep -c "T ? F" res_dnS`
if test $nb_pb1 -gt 0 -o $nb_pb2 -gt 0
then
   echo "Error(s) detected!!"
else
   echo "No error!"
fi
echo ""

echo "TESTING functions with or without analitical derivatives"

nb_pb=`awk '/==0\?/ {print $3}' res_dnS | grep -c F`
if test $nb_pb -gt 0
then
   echo "Error(s) detected!!"
else
   echo "No error!"
fi
echo ""

echo "TESTING dnSca.txt with respect to old results"
../bin/Compare_dnSca > Test_dnSca.log


#grep "The structure of both files are different" Test_dnSca.log
nb_e=`grep -c "The structure of both files are different" Test_dnSca.log`
if test $nb_e -gt 0
then
   echo "  Warning: different dnSca.txt file structure!!"
else
   echo "  No Warning: identical dnSca.txt file structure!"
fi
echo ""


grep "PROBLEM" Test_dnSca.log
nb_pb=`grep -c "PROBLEM(S)" Test_dnSca.log`

if test $nb_pb -gt 0
then
   echo "Error(s) detected!!"
else
   echo "No error!"
fi

echo "=========================================="
